f = open("data.txt", encoding="utf-8")
aa = f.read().split(' ')
a, b = int(aa[0]), int(aa[1])
# a , b = int(f.read()),int(f.read())
print (a + b)
print (a - b)
print (a * b)
print (a // b)
print (a % b)